export default Languages = {
    en : {
        Home: "Home",
        "Welcome to Home page" : "Welcome to Home page",
        News: "News",
        Calculator: "Calculator",
        Machines: "Machines",
        "Trade Fair": "Trade Fair",
        "Remaining warp calculater" : "Remaining warp calculator",
        "Yarn count converter" : "Yarn count converter",
        "Fabric length & weight calculater" : "Fabric length & weight calculator",
        "Cover factor calculater" : "Cover factor calculator",
        "Yarn diameter & count calculater" : "Yarn diameter & count calculator",
        "Warp Material" : "Warp Material",
        "Count Unit" : "Count Unit",
        "Yarn number single yarn" : "Yarn number single yarn",
        Ply: "Ply",
        "Warp ends/cm" : "Warp ends/cm",
        "Outside diameter warp beam barrel": "Outside diameter warp beam barrel",
        "Outside diameter warp beam flange" : "Outside diameter warp beam flange",
        "Distance between outside flange and warp yarn": "Distance between outside flange and warp yarn",
        "Distance between flanges" : "Distance between flanges",
        "Warp weight" : "Warp weight",
        "Loom width" : "Loom width",
        "Beam type" : "Beam type",
        "Flange quality" : "Flange quality",
        Material: "Material",
        "Number of filaments": "Number of filaments",
        "Yarn Diameter" : "Yarn Diameter",
        "Yarn Number" : "Yarn Number",
        "Warp count" : "Warp count",
        "Warp end" : "Warp end",
        "Welf Material": "Welf Material",
        "Welf count": "Welf count",
        "Welf Picks" : "Welf Picks",
        "Weave" : "Weave",
        Width: "Width",
        "Inner diameter d cloth roller": "Inner diameter d cloth roller",
        "Distance R to tube": "Distance R to tube",
        "Outer diameter D cloth roller" : "Outer diameter D cloth roller",
        "Cloth length" : "Cloth length",
        "Cloth weight" : "Cloth weight",
        "Warp length remaining" : "Warp length remaining",
        "remaining_warp_description_primary" : "During the weaving process it can be useful or even necessary to know how many meters of fabric can still be woven with the yarn left on the warp beam.",
        "remaining_warp_description_secondary" : "By entering some basic data such as yarn count, number of ends, tube and flange diameter etc. you can estimate the length and weight of the yarn still remaining on the beam.",
        "remaining_warp_short_description" : "Calculates the remaining length and weight of yarn on the warp beam.",
        
        "cover_factor_description_primary" : "This tool allows you to calculate the Cover Factor of most fabrics. All you need to do is enter the basic fabric specification and choose the weaving pattern.",
        "cover_factor_description_secondary" : "The cover factor is a parameter that gives an indication of how dense or heavy a given fabric is. It also allows you to compare it to other fabrics and eventually decide if it is possible to weave or not.",
        "cover_factor_short_description" : "Gives an indication of how dense or heavy a given fabric is, thus allowing you to compare it to other fabrics and decide if it is possible to weave or not.",

        "fabric_length_description_primary" : "By simply entering some basic fabric data as well as the dimensions of the cloth roll, this calculator will give you an estimation of the fabric length on the roll as well as the  weight of the roll.",
        "fabric_length_short_description" : "Estimates the weight of the cloth roller as well of the length of fabric on it.",
        
        "yarn_diameter_description_primary" : "This calculator makes it possible to get an idea of the yarn count of a fabric based on the yarn diameter. Or, the other way around, it can give you an estimation of its yarn diameter based on the yarn count.",
        "yarn_diameter_short_description" : "Get an idea of the yarn count of a fabric based on its yarn diameter or, the other way around, an estimation of the yarn diameter based on the fabrics’ yarn count.",

        "yarn_count_description_primary" : "Converts different yarns to their equivalents in other counts.",

    }
}